# ????????? hibernate
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
# ????? create ??? update: ?????? ?????? ?? ?????????????, ? ???????????
hibernate.hbm2ddl.auto=update

# ????????? ???? ??????
db.driver=org.postgresql.Driver
db.url=jdbc:postgresql://localhost:5432/MTConnectData
db.username=appuser
db.password=rwyh123

# ????????? MTConnect
mtconnect.url=http://localhost:5050/mtconnect/current
mtconnect.poll-ms= 25
mtconnect.ingest-ms: 25
mtconnect.http.connect-timeout-ms=2000
mtconnect.http.read-timeout-ms=4000

# ???? ???-???????
server.port=8080

# ????????? ??????????? Thymeleaf
spring.thymeleaf.cache=false

# ????? ?? ??? ??????
app.clear-db-on-start=true

# ?????? ??? ??????? ??? ?? ????????
cnc.thresholds.[z_temp]=42.5
cnc.thresholds.[y_temp]=40.5
cnc.thresholds.[x_temp]=40.5
cnc.thresholds.[spindle_temp]=56.0
cnc.thresholds.[spindle_smoothed_speed_rpm]=3020.0
cnc.thresholds.[spindle_speed_rpm]=3030.0
cnc.thresholds.[ElectricCurrent_1]=12.5
cnc.thresholds.[Voltage_1]=226.0
cnc.thresholds.[Power_1]=6.2
cnc.thresholds.[Torque_1]=25.5
